-- migration_008_currencies_full.sql
-- Upsert 255 ISO 4217 currencies (active + historic)
-- Preserves existing name_uk and symbol values

INSERT INTO currencies (code, name_en, status, valid_from, valid_to, replaced_by_code, numeric_code)
VALUES
  ('AED', 'UAE Dirham', 'active', NULL, NULL, NULL, '784'),
  ('AFN', 'Afghani', 'active', NULL, NULL, NULL, '971'),
  ('ALL', 'Lek', 'active', NULL, NULL, NULL, '008'),
  ('AMD', 'Armenian Dram', 'active', NULL, NULL, NULL, '051'),
  ('ANG', 'Netherlands Antillean Guilder', 'active', NULL, NULL, NULL, '532'),
  ('AOA', 'Kwanza', 'active', NULL, NULL, NULL, '973'),
  ('ARS', 'Argentine Peso', 'active', NULL, NULL, NULL, '032'),
  ('AUD', 'Australian Dollar', 'active', NULL, NULL, NULL, '036'),
  ('AWG', 'Aruban Florin', 'active', NULL, NULL, NULL, '533'),
  ('AZN', 'Azerbaijan Manat', 'active', NULL, NULL, NULL, '944'),
  ('BAM', 'Convertible Mark', 'active', NULL, NULL, NULL, '977'),
  ('BBD', 'Barbados Dollar', 'active', NULL, NULL, NULL, '052'),
  ('BDT', 'Taka', 'active', NULL, NULL, NULL, '050'),
  ('BGN', 'Bulgarian Lev', 'active', NULL, NULL, NULL, '975'),
  ('BHD', 'Bahraini Dinar', 'active', NULL, NULL, NULL, '048'),
  ('BIF', 'Burundi Franc', 'active', NULL, NULL, NULL, '108'),
  ('BMD', 'Bermudian Dollar', 'active', NULL, NULL, NULL, '060'),
  ('BND', 'Brunei Dollar', 'active', NULL, NULL, NULL, '096'),
  ('BOB', 'Boliviano', 'active', NULL, NULL, NULL, '068'),
  ('BOV', 'Mvdol', 'active', NULL, NULL, NULL, '984'),
  ('BRL', 'Brazilian Real', 'active', NULL, NULL, NULL, '986'),
  ('BSD', 'Bahamian Dollar', 'active', NULL, NULL, NULL, '044'),
  ('BTN', 'Ngultrum', 'active', NULL, NULL, NULL, '064'),
  ('BWP', 'Pula', 'active', NULL, NULL, NULL, '072'),
  ('BYN', 'Belarusian Ruble', 'active', NULL, NULL, NULL, '933'),
  ('BZD', 'Belize Dollar', 'active', NULL, NULL, NULL, '084'),
  ('CAD', 'Canadian Dollar', 'active', NULL, NULL, NULL, '124'),
  ('CDF', 'Congolese Franc', 'active', NULL, NULL, NULL, '976'),
  ('CHE', 'WIR Euro', 'active', NULL, NULL, NULL, '947'),
  ('CHF', 'Swiss Franc', 'active', NULL, NULL, NULL, '756'),
  ('CHW', 'WIR Franc', 'active', NULL, NULL, NULL, '948'),
  ('CLF', 'Unidad de Fomento', 'active', NULL, NULL, NULL, '990'),
  ('CLP', 'Chilean Peso', 'active', NULL, NULL, NULL, '152'),
  ('CNY', 'Yuan Renminbi', 'active', NULL, NULL, NULL, '156'),
  ('COP', 'Colombian Peso', 'active', NULL, NULL, NULL, '170'),
  ('COU', 'Unidad de Valor Real', 'active', NULL, NULL, NULL, '970'),
  ('CRC', 'Costa Rican Colon', 'active', NULL, NULL, NULL, '188'),
  ('CUP', 'Cuban Peso', 'active', NULL, NULL, NULL, '192'),
  ('CVE', 'Cabo Verde Escudo', 'active', NULL, NULL, NULL, '132'),
  ('CZK', 'Czech Koruna', 'active', NULL, NULL, NULL, '203'),
  ('DJF', 'Djibouti Franc', 'active', NULL, NULL, NULL, '262'),
  ('DKK', 'Danish Krone', 'active', NULL, NULL, NULL, '208'),
  ('DOP', 'Dominican Peso', 'active', NULL, NULL, NULL, '214'),
  ('DZD', 'Algerian Dinar', 'active', NULL, NULL, NULL, '012'),
  ('EGP', 'Egyptian Pound', 'active', NULL, NULL, NULL, '818'),
  ('ERN', 'Nakfa', 'active', NULL, NULL, NULL, '232'),
  ('ETB', 'Ethiopian Birr', 'active', NULL, NULL, NULL, '230'),
  ('EUR', 'Euro', 'active', NULL, NULL, NULL, '978'),
  ('FJD', 'Fiji Dollar', 'active', NULL, NULL, NULL, '242'),
  ('FKP', 'Falkland Islands Pound', 'active', NULL, NULL, NULL, '238'),
  ('GBP', 'Pound Sterling', 'active', NULL, NULL, NULL, '826'),
  ('GEL', 'Lari', 'active', NULL, NULL, NULL, '981'),
  ('GHS', 'Ghana Cedi', 'active', NULL, NULL, NULL, '936'),
  ('GIP', 'Gibraltar Pound', 'active', NULL, NULL, NULL, '292'),
  ('GMD', 'Dalasi', 'active', NULL, NULL, NULL, '270'),
  ('GNF', 'Guinean Franc', 'active', NULL, NULL, NULL, '324'),
  ('GTQ', 'Quetzal', 'active', NULL, NULL, NULL, '320'),
  ('GYD', 'Guyana Dollar', 'active', NULL, NULL, NULL, '328'),
  ('HKD', 'Hong Kong Dollar', 'active', NULL, NULL, NULL, '344'),
  ('HNL', 'Lempira', 'active', NULL, NULL, NULL, '340'),
  ('HTG', 'Gourde', 'active', NULL, NULL, NULL, '332'),
  ('HUF', 'Forint', 'active', NULL, NULL, NULL, '348'),
  ('IDR', 'Rupiah', 'active', NULL, NULL, NULL, '360'),
  ('ILS', 'New Israeli Sheqel', 'active', NULL, NULL, NULL, '376'),
  ('INR', 'Indian Rupee', 'active', NULL, NULL, NULL, '356'),
  ('IQD', 'Iraqi Dinar', 'active', NULL, NULL, NULL, '368'),
  ('IRR', 'Iranian Rial', 'active', NULL, NULL, NULL, '364'),
  ('ISK', 'Iceland Krona', 'active', NULL, NULL, NULL, '352'),
  ('JMD', 'Jamaican Dollar', 'active', NULL, NULL, NULL, '388'),
  ('JOD', 'Jordanian Dinar', 'active', NULL, NULL, NULL, '400'),
  ('JPY', 'Yen', 'active', NULL, NULL, NULL, '392'),
  ('KES', 'Kenyan Shilling', 'active', NULL, NULL, NULL, '404'),
  ('KGS', 'Som', 'active', NULL, NULL, NULL, '417'),
  ('KHR', 'Riel', 'active', NULL, NULL, NULL, '116'),
  ('KMF', 'Comorian Franc', 'active', NULL, NULL, NULL, '174'),
  ('KPW', 'North Korean Won', 'active', NULL, NULL, NULL, '408'),
  ('KRW', 'Won', 'active', NULL, NULL, NULL, '410'),
  ('KWD', 'Kuwaiti Dinar', 'active', NULL, NULL, NULL, '414'),
  ('KYD', 'Cayman Islands Dollar', 'active', NULL, NULL, NULL, '136'),
  ('KZT', 'Tenge', 'active', NULL, NULL, NULL, '398'),
  ('LAK', 'Lao Kip', 'active', NULL, NULL, NULL, '418'),
  ('LBP', 'Lebanese Pound', 'active', NULL, NULL, NULL, '422'),
  ('LKR', 'Sri Lanka Rupee', 'active', NULL, NULL, NULL, '144'),
  ('LRD', 'Liberian Dollar', 'active', NULL, NULL, NULL, '430'),
  ('LSL', 'Loti', 'active', NULL, NULL, NULL, '426'),
  ('LYD', 'Libyan Dinar', 'active', NULL, NULL, NULL, '434'),
  ('MAD', 'Moroccan Dirham', 'active', NULL, NULL, NULL, '504'),
  ('MDL', 'Moldovan Leu', 'active', NULL, NULL, NULL, '498'),
  ('MGA', 'Malagasy Ariary', 'active', NULL, NULL, NULL, '969'),
  ('MKD', 'Denar', 'active', NULL, NULL, NULL, '807'),
  ('MMK', 'Kyat', 'active', NULL, NULL, NULL, '104'),
  ('MNT', 'Tugrik', 'active', NULL, NULL, NULL, '496'),
  ('MOP', 'Pataca', 'active', NULL, NULL, NULL, '446'),
  ('MRU', 'Ouguiya', 'active', NULL, NULL, NULL, '929'),
  ('MUR', 'Mauritius Rupee', 'active', NULL, NULL, NULL, '480'),
  ('MVR', 'Rufiyaa', 'active', NULL, NULL, NULL, '462'),
  ('MWK', 'Malawi Kwacha', 'active', NULL, NULL, NULL, '454'),
  ('MXN', 'Mexican Peso', 'active', NULL, NULL, NULL, '484'),
  ('MXV', 'Mexican Unidad de Inversion (UDI)', 'active', NULL, NULL, NULL, '979'),
  ('MYR', 'Malaysian Ringgit', 'active', NULL, NULL, NULL, '458'),
  ('MZN', 'Mozambique Metical', 'active', NULL, NULL, NULL, '943'),
  ('NAD', 'Namibia Dollar', 'active', NULL, NULL, NULL, '516'),
  ('NGN', 'Naira', 'active', NULL, NULL, NULL, '566'),
  ('NIO', 'Cordoba Oro', 'active', NULL, NULL, NULL, '558'),
  ('NOK', 'Norwegian Krone', 'active', NULL, NULL, NULL, '578'),
  ('NPR', 'Nepalese Rupee', 'active', NULL, NULL, NULL, '524'),
  ('NZD', 'New Zealand Dollar', 'active', NULL, NULL, NULL, '554'),
  ('OMR', 'Rial Omani', 'active', NULL, NULL, NULL, '512'),
  ('PAB', 'Balboa', 'active', NULL, NULL, NULL, '590'),
  ('PEN', 'Sol', 'active', NULL, NULL, NULL, '604'),
  ('PGK', 'Kina', 'active', NULL, NULL, NULL, '598'),
  ('PHP', 'Philippine Peso', 'active', NULL, NULL, NULL, '608'),
  ('PKR', 'Pakistan Rupee', 'active', NULL, NULL, NULL, '586'),
  ('PLN', 'Zloty', 'active', NULL, NULL, NULL, '985'),
  ('PYG', 'Guarani', 'active', NULL, NULL, NULL, '600'),
  ('QAR', 'Qatari Rial', 'active', NULL, NULL, NULL, '634'),
  ('RON', 'Romanian Leu', 'active', NULL, NULL, NULL, '946'),
  ('RSD', 'Serbian Dinar', 'active', NULL, NULL, NULL, '941'),
  ('RUB', 'Russian Ruble', 'active', NULL, NULL, NULL, '643'),
  ('RWF', 'Rwanda Franc', 'active', NULL, NULL, NULL, '646'),
  ('SAR', 'Saudi Riyal', 'active', NULL, NULL, NULL, '682'),
  ('SBD', 'Solomon Islands Dollar', 'active', NULL, NULL, NULL, '090'),
  ('SCR', 'Seychelles Rupee', 'active', NULL, NULL, NULL, '690'),
  ('SDG', 'Sudanese Pound', 'active', NULL, NULL, NULL, '938'),
  ('SEK', 'Swedish Krona', 'active', NULL, NULL, NULL, '752'),
  ('SGD', 'Singapore Dollar', 'active', NULL, NULL, NULL, '702'),
  ('SHP', 'Saint Helena Pound', 'active', NULL, NULL, NULL, '654'),
  ('SLE', 'Leone', 'active', NULL, NULL, NULL, '925'),
  ('SLL', 'Leone', 'active', NULL, NULL, NULL, '694'),
  ('SOS', 'Somali Shilling', 'active', NULL, NULL, NULL, '706'),
  ('SRD', 'Surinam Dollar', 'active', NULL, NULL, NULL, '968'),
  ('SSP', 'South Sudanese Pound', 'active', NULL, NULL, NULL, '728'),
  ('STN', 'Dobra', 'active', NULL, NULL, NULL, '930'),
  ('SVC', 'El Salvador Colon', 'active', NULL, NULL, NULL, '222'),
  ('SYP', 'Syrian Pound', 'active', NULL, NULL, NULL, '760'),
  ('SZL', 'Lilangeni', 'active', NULL, NULL, NULL, '748'),
  ('THB', 'Baht', 'active', NULL, NULL, NULL, '764'),
  ('TJS', 'Somoni', 'active', NULL, NULL, NULL, '972'),
  ('TMT', 'Turkmenistan New Manat', 'active', NULL, NULL, NULL, '934'),
  ('TND', 'Tunisian Dinar', 'active', NULL, NULL, NULL, '788'),
  ('TOP', 'Pa’anga', 'active', NULL, NULL, NULL, '776'),
  ('TRY', 'Turkish Lira', 'active', NULL, NULL, NULL, '949'),
  ('TTD', 'Trinidad and Tobago Dollar', 'active', NULL, NULL, NULL, '780'),
  ('TWD', 'New Taiwan Dollar', 'active', NULL, NULL, NULL, '901'),
  ('TZS', 'Tanzanian Shilling', 'active', NULL, NULL, NULL, '834'),
  ('UAH', 'Hryvnia', 'active', NULL, NULL, NULL, '980'),
  ('UGX', 'Uganda Shilling', 'active', NULL, NULL, NULL, '800'),
  ('USD', 'US Dollar', 'active', NULL, NULL, NULL, '840'),
  ('USN', 'US Dollar (Next day)', 'active', NULL, NULL, NULL, '997'),
  ('UYI', 'Uruguay Peso en Unidades Indexadas (UI)', 'active', NULL, NULL, NULL, '940'),
  ('UYU', 'Peso Uruguayo', 'active', NULL, NULL, NULL, '858'),
  ('UYW', 'Unidad Previsional', 'active', NULL, NULL, NULL, '927'),
  ('UZS', 'Uzbekistan Sum', 'active', NULL, NULL, NULL, '860'),
  ('VED', 'Bolívar Soberano', 'active', NULL, NULL, NULL, '926'),
  ('VES', 'Bolívar Soberano', 'active', NULL, NULL, NULL, '928'),
  ('VND', 'Dong', 'active', NULL, NULL, NULL, '704'),
  ('VUV', 'Vatu', 'active', NULL, NULL, NULL, '548'),
  ('WST', 'Tala', 'active', NULL, NULL, NULL, '882'),
  ('XAF', 'CFA Franc BEAC', 'active', NULL, NULL, NULL, '950'),
  ('XAG', 'Silver', 'active', NULL, NULL, NULL, '961'),
  ('XAU', 'Gold', 'active', NULL, NULL, NULL, '959'),
  ('XBA', 'Bond Markets Unit European Composite Unit (EURCO)', 'active', NULL, NULL, NULL, '955'),
  ('XBB', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'active', NULL, NULL, NULL, '956'),
  ('XBC', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'active', NULL, NULL, NULL, '957'),
  ('XBD', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'active', NULL, NULL, NULL, '958'),
  ('XCD', 'East Caribbean Dollar', 'active', NULL, NULL, NULL, '951'),
  ('XDR', 'SDR (Special Drawing Right)', 'active', NULL, NULL, NULL, '960'),
  ('XOF', 'CFA Franc BCEAO', 'active', NULL, NULL, NULL, '952'),
  ('XPD', 'Palladium', 'active', NULL, NULL, NULL, '964'),
  ('XPF', 'CFP Franc', 'active', NULL, NULL, NULL, '953'),
  ('XPT', 'Platinum', 'active', NULL, NULL, NULL, '962'),
  ('XSU', 'Sucre', 'active', NULL, NULL, NULL, '994'),
  ('XTS', 'Codes specifically reserved for testing purposes', 'active', NULL, NULL, NULL, '963'),
  ('XUA', 'ADB Unit of Account', 'active', NULL, NULL, NULL, '965'),
  ('XXX', 'The codes assigned for transactions where no currency is involved', 'active', NULL, NULL, NULL, '999'),
  ('YER', 'Yemeni Rial', 'active', NULL, NULL, NULL, '886'),
  ('ZAR', 'Rand', 'active', NULL, NULL, NULL, '710'),
  ('ZMW', 'Zambian Kwacha', 'active', NULL, NULL, NULL, '967'),
  ('ZWG', NULL, 'active', NULL, NULL, NULL, NULL),
  ('ADP', 'Andorran peseta', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '020'),
  ('AFA', 'Afghan afghani (old)', 'historic_or_obsolete', NULL, '2003-01', 'AFN', '004'),
  ('ALK', 'Albanian lek (old)', 'historic_or_obsolete', NULL, NULL, 'ALL', '008'),
  ('AON', 'Angolan new kwanza', 'historic_or_obsolete', '1990', '1995', 'AOR', '024'),
  ('AOR', 'Angolan kwanza reajustado', 'historic_or_obsolete', '1995', '1999', 'AOA', '982'),
  ('ARA', 'Argentine austral', 'historic_or_obsolete', '1985', '1992', 'ARS', '032'),
  ('ARP', 'Argentine peso argentino', 'historic_or_obsolete', '1983', '1985', 'ARA', '032'),
  ('ATS', 'Austrian schilling', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '040'),
  ('AZM', 'Azerbaijani manat', 'historic_or_obsolete', '1993', '2005-12-31', 'AZN', '031'),
  ('BEC', 'Belgian franc convertible', 'historic_or_obsolete', NULL, '1990', 'BEF', '993'),
  ('BEF', 'Belgian franc', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '056'),
  ('BEL', 'Belgian franc financial', 'historic_or_obsolete', NULL, '1990', 'BEF', '992'),
  ('BGJ', 'Bulgarian lev A/52', 'historic_or_obsolete', NULL, NULL, 'BGK', '100'),
  ('BGK', 'Bulgarian lev A/62', 'historic_or_obsolete', NULL, NULL, 'BGL', '100'),
  ('BGL', 'Bulgarian lev', 'historic_or_obsolete', NULL, '1999-07-05', 'BGN', '100'),
  ('BOP', 'Bolivian peso', 'historic_or_obsolete', NULL, '1987', 'BOB', '068'),
  ('BRB', 'Brazilian cruzeiro novo', 'historic_or_obsolete', '1967', '1986', 'BRC', '076'),
  ('BRC', 'Brazilian cruzado', 'historic_or_obsolete', '1986', '1989', 'BRN', '076'),
  ('BRE', 'Brazilian cruzeiro', 'historic_or_obsolete', '1990', '1993', 'BRR', '076'),
  ('BRN', 'Brazilian cruzado novo', 'historic_or_obsolete', '1989', '1990', 'BRE', '076'),
  ('BRR', 'Brazilian cruzeiro real', 'historic_or_obsolete', '1993', '1994', 'BRL', '987'),
  ('BYB', 'Belarusian ruble', 'historic_or_obsolete', '1992', '1999-12-31', 'BYR', '112'),
  ('BYR', 'Belarusian ruble', 'historic_or_obsolete', '2000-01-01', '2016-06-30', 'BYN', '974'),
  ('CSD', 'Serbian dinar', 'historic_or_obsolete', '2003-07-03', '2006-10-25', 'RSD', '891'),
  ('CSJ', 'Czechoslovak koruna (second)', 'historic_or_obsolete', NULL, '1953', 'CSK', '203'),
  ('CSK', 'Czechoslovak koruna', 'historic_or_obsolete', '1953', '1993-02-08', 'CZK/SKK', '200'),
  ('CUC', 'Cuban convertible peso', 'historic_or_obsolete', '2009-03-01', '2021-06-30', 'CUP', '931'),
  ('CYP', 'Cypriot pound', 'historic_or_obsolete', '1879', '2008-01-01', 'EUR', '196'),
  ('DDM', 'East German mark', 'historic_or_obsolete', '1948-06-21', '1990-07-01', 'DEM', '278'),
  ('DEM', 'German mark', 'historic_or_obsolete', '1948', '2002-02-28', 'EUR', '276'),
  ('ECS', 'Ecuadorian sucre', 'historic_or_obsolete', '1884', '2000-02-29', 'USD', '218'),
  ('EEK', 'Estonian kroon', 'historic_or_obsolete', '1992', '2011-01-01', 'EUR', '233'),
  ('ESP', 'Spanish peseta', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '724'),
  ('FIM', 'Finnish markka', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '246'),
  ('FRF', 'French franc', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '250'),
  ('GHC', 'Ghanaian cedi', 'historic_or_obsolete', '1965', '2007-07-01', 'GHS', '288'),
  ('GRD', 'Greek drachma', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '300'),
  ('HRD', 'Croatian dinar', 'historic_or_obsolete', '1991', '1994-05-30', 'HRK', '191'),
  ('HRK', 'Croatian kuna', 'historic_or_obsolete', '1994-05-30', '2023-01-01', 'EUR', '191'),
  ('IEP', 'Irish pound', 'historic_or_obsolete', '1938', '2002-02-09', 'EUR', '372'),
  ('ILP', 'Israeli pound', 'historic_or_obsolete', '1948', '1980-02-20', 'ILR', '376'),
  ('ILR', 'Israeli shekel', 'historic_or_obsolete', '1980-02-24', '1985-12-31', 'ILS', '376'),
  ('ISJ', 'Icelandic króna (old)', 'historic_or_obsolete', '1922', '1981-06-30', 'ISK', '352'),
  ('ITL', 'Italian lira', 'historic_or_obsolete', '1861', '2002-02-28', 'EUR', '380'),
  ('LTL', 'Lithuanian litas', 'historic_or_obsolete', '1993', '2015-01-01', 'EUR', '440'),
  ('LVL', 'Latvian lats', 'historic_or_obsolete', '1993-03-05', '2014-01-01', 'EUR', '428'),
  ('MGF', 'Malagasy franc', 'historic_or_obsolete', '1963-07-01', '2005-01-01', 'MGA', '450'),
  ('MRO', 'Mauritanian ouguiya', 'historic_or_obsolete', '1973-06-29', '2018-01-01', 'MRU', '478'),
  ('MTL', 'Maltese lira', 'historic_or_obsolete', NULL, '2008-01-01', 'EUR', '470'),
  ('MXP', 'Mexican peso (old)', 'historic_or_obsolete', NULL, '1993-01-01', 'MXN', '484'),
  ('NLG', 'Netherlands guilder', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '528'),
  ('PEI', 'Peruvian inti', 'historic_or_obsolete', '1985', '1991', 'PEN', '604'),
  ('PES', 'Peruvian sol', 'historic_or_obsolete', NULL, '1985', 'PEI', '604'),
  ('PLZ', 'Polish zloty (old)', 'historic_or_obsolete', NULL, '1995-01-01', 'PLN', '616'),
  ('PTE', 'Portuguese escudo', 'historic_or_obsolete', NULL, '2002-02-28', 'EUR', '620'),
  ('ROL', 'Romanian leu', 'historic_or_obsolete', NULL, '2005-07-01', 'RON', '642'),
  ('RUR', 'Russian ruble (old)', 'historic_or_obsolete', NULL, '1998-01-01', 'RUB', '810'),
  ('SDD', 'Sudanese dinar', 'historic_or_obsolete', NULL, '2007', 'SDG', '736'),
  ('SIT', 'Slovenian tolar', 'historic_or_obsolete', '1991', '2007-01-01', 'EUR', '705'),
  ('SKK', 'Slovak koruna', 'historic_or_obsolete', '1993', '2009-01-01', 'EUR', '703'),
  ('SRG', 'Surinamese guilder', 'historic_or_obsolete', NULL, '2004-01-01', 'SRD', '740'),
  ('TMM', 'Turkmenistani manat', 'historic_or_obsolete', '1993', '2009-01-01', 'TMT', '795'),
  ('TRL', 'Turkish lira (old)', 'historic_or_obsolete', NULL, '2005-01-01', 'TRY', '792'),
  ('UAK', 'Ukrainian karbovanets', 'historic_or_obsolete', '1992', '1996-09-02', 'UAH', '804'),
  ('USS', 'US dollar, same day funds', 'historic_or_obsolete', NULL, '2014-03-01', 'USD', '998'),
  ('VEB', 'Venezuelan bolívar', 'historic_or_obsolete', NULL, '2008-01-01', 'VEF', '862'),
  ('VEF', 'Venezuelan bolívar fuerte', 'historic_or_obsolete', '2008-01-01', '2018-08-20', 'VES', '937'),
  ('YDD', 'South Yemeni dinar', 'historic_or_obsolete', NULL, '1996', 'YER', '720'),
  ('YUM', 'Yugoslav dinar', 'historic_or_obsolete', '1994', '2003', 'CSD/RSD', '891'),
  ('ZMK', 'Zambian kwacha', 'historic_or_obsolete', NULL, '2013-01-01', 'ZMW', '894'),
  ('ZRN', 'Zairean new zaire', 'historic_or_obsolete', '1993', '1997', 'CDF', '180'),
  ('ZRZ', 'Zairean zaire', 'historic_or_obsolete', '1967', '1993', 'ZRN/CDF', '180'),
  ('ZWD', 'Zimbabwean dollar (first)', 'historic_or_obsolete', '1980-04-18', '2006-07-31', 'ZWN', '716'),
  ('ZWL', 'Zimbabwean dollar / RTGS dollar', 'historic_or_obsolete', '2009-02-02', '2024-04-08', 'ZWG', '932'),
  ('ZWN', 'Zimbabwean dollar (second)', 'historic_or_obsolete', '2006-08-01', '2008-07-31', 'ZWR', '942'),
  ('ZWR', 'Zimbabwean dollar (third)', 'historic_or_obsolete', '2008-08-01', '2009-02-02', 'ZWL', '935')
ON CONFLICT (code) DO UPDATE SET
  name_en          = COALESCE(EXCLUDED.name_en, currencies.name_en),
  status           = EXCLUDED.status,
  valid_from       = EXCLUDED.valid_from,
  valid_to         = EXCLUDED.valid_to,
  replaced_by_code = EXCLUDED.replaced_by_code,
  numeric_code     = EXCLUDED.numeric_code;
-- name_uk and symbol are NOT overwritten to preserve manual translations
